spring:
  datasource:
    username: postgres
    password: developer
    url: jdbc:postgresql://localhost:5432/product

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  application:
    name: inventory-service
server:
  port: 8082

#axon:
#  axonserver:
#    servers: localhost
